spring.application.name=backend
server.port=8080

# Local MongoDB Configuration
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=student_performance_ranking_db
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/student_performance_ranking_db

logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.example.backend=DEBUG
