spring.application.name=backend
server.port=8080

# Local MongoDB Configuration
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=student_performance_ranking_db
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/student_performance_ranking_db

# Jackson JSON Deserialization Configuration (Prevents HTTP 400 Bad Request on null numbers)
spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false
spring.jackson.deserialization.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT=true
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=false

logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.example.backend=DEBUG
